import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";
import { toast } from "sonner";

export interface GroupMember {
  id: string;
  user_id: string;
  name: string;
}

interface PublicProfile {
  id: string;
  user_id: string;
  name: string;
}

interface GroupInsert {
  name: string;
  is_temporary: boolean;
}

export interface Group {
  id: string;
  name: string;
  is_temporary: boolean;
  created_by: string;
  created_at: string;
  invite_code: string;
  members: GroupMember[];
}

export function useGroups() {
  const { user } = useAuth();
  const [groups, setGroups] = useState<Group[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchGroups = useCallback(async () => {
    if (!user) {
      setGroups([]);
      setLoading(false);
      return;
    }

    try {
      // Use RPC function to fetch groups with members (bypasses RLS issues)
      const { data, error } = await supabase.rpc("get_user_groups");

      if (error) throw error;

      if (!data || data.length === 0) {
        setGroups([]);
        setLoading(false);
        return;
      }

      // Build a map of group_id -> members
      const groupMembersMap = new Map<string, GroupMember[]>();
      const groupsMap = new Map<string, Group>();

      data.forEach((row: any) => {
        // Create or update group entry
        if (!groupsMap.has(row.group_id)) {
          groupsMap.set(row.group_id, {
            id: row.group_id,
            name: row.group_name,
            is_temporary: row.group_is_temporary,
            created_by: row.group_created_by,
            created_at: row.group_created_at,
            invite_code: row.group_invite_code,
            members: [],
          });
          groupMembersMap.set(row.group_id, []);
        }

        // Add member if profile data is valid
        if (row.member_id && row.member_user_id && row.member_name) {
          const members = groupMembersMap.get(row.group_id)!;

          // Avoid duplicates (same member might appear multiple times)
          if (!members.some(m => m.user_id === row.member_user_id)) {
            members.push({
              id: row.member_id,
              user_id: row.member_user_id,
              name: row.member_name,
            });
          }
        }
      });

      // Assign members to groups
      const groupsWithMembers: Group[] = Array.from(groupsMap.values()).map(
        (group) => ({
          ...group,
          members: groupMembersMap.get(group.id) || [],
        })
      );

      setGroups(groupsWithMembers);
    } catch (error) {
      console.error("Error fetching groups:", error);
      toast.error("Kunde inte hämta grupper");
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    fetchGroups();
  }, [fetchGroups]);

  const createGroup = async (name: string, isTemporary: boolean = false, selectedUserIds: string[] = []) => {
    if (!user) {
      toast.error("Du måste vara inloggad");
      return null;
    }

    try {
      // Create the group - member and invite_code are auto-added via database triggers
      // invite_code is generated by a trigger, so we cast to bypass TypeScript requirement
      const { data: groupData, error: groupError } = await supabase
        .from("groups")
        .insert({
          name,
          is_temporary: isTemporary,
        } as { name: string; is_temporary: boolean; invite_code: string })
        .select()
        .single();

      if (groupError) {
        console.error("Group creation error:", groupError.code, groupError.message);
        throw groupError;
      }

      // Add selected users as members
      if (selectedUserIds.length > 0) {
        const membersToAdd = selectedUserIds.map(userId => ({
          group_id: groupData.id,
          user_id: userId,
        }));

        const { error: membersError } = await supabase
          .from("group_members")
          .insert(membersToAdd);

        if (membersError) {
          console.error("Error adding members:", membersError);
          toast.error("Grupp skapad men kunde inte lägga till alla medlemmar");
        }
      }

      await fetchGroups();
      toast.success("Grupp skapad!");
      return groupData;
    } catch (error) {
      console.error("Error creating group:", error);
      const errorMessage = error instanceof Error ? error.message : "Kunde inte skapa grupp";
      toast.error(errorMessage);
      return null;
    }
  };

  const deleteGroup = async (groupId: string) => {
    try {
      const { error } = await supabase
        .from("groups")
        .delete()
        .eq("id", groupId);

      if (error) throw error;

      await fetchGroups();
      toast.success("Grupp borttagen");
    } catch (error) {
      console.error("Error deleting group:", error);
      toast.error("Kunde inte ta bort grupp");
    }
  };

  const addMembers = async (groupId: string, userIds: string[]) => {
    try {
      const membersToAdd = userIds.map(userId => ({
        group_id: groupId,
        user_id: userId,
      }));

      const { error } = await supabase
        .from("group_members")
        .insert(membersToAdd);

      if (error) {
        console.error("Error adding members:", error);
        console.error("Error details:", {
          code: error.code,
          message: error.message,
          details: error.details,
          hint: error.hint,
        });
        throw error;
      }

      await fetchGroups();
      toast.success(`${userIds.length} ${userIds.length === 1 ? 'medlem' : 'medlemmar'} tillagd${userIds.length === 1 ? '' : 'a'}!`);
    } catch (error) {
      console.error("Error adding members:", error);
      const errorMessage = error instanceof Error 
        ? error.message 
        : "Kunde inte lägga till medlemmar";
      toast.error(errorMessage);
    }
  };

  const removeMember = async (groupId: string, userId: string) => {
    try {
      const { error } = await supabase.rpc("remove_group_member", {
        group_id_param: groupId,
        user_id_param: userId,
      }) as { data: boolean | null; error: Error | null };

      if (error) {
        console.error("Error removing member:", error);
        throw error;
      }

      await fetchGroups();
      toast.success("Medlem borttagen");
    } catch (error) {
      console.error("Error removing member:", error);
      const errorMessage = error instanceof Error 
        ? error.message 
        : "Kunde inte ta bort medlem";
      toast.error(errorMessage);
    }
  };

  const regenerateInviteCode = async (groupId: string) => {
    try {
      const { data: newCode, error } = await supabase.rpc("regenerate_invite_code", {
        group_id_param: groupId,
      }) as { data: string | null; error: Error | null };

      if (error) {
        console.error("Error regenerating invite code:", error);
        throw error;
      }

      await fetchGroups();
      toast.success("Ny inbjudningskod genererad");
      return newCode;
    } catch (error) {
      console.error("Error regenerating invite code:", error);
      const errorMessage = error instanceof Error 
        ? error.message 
        : "Kunde inte generera ny kod";
      toast.error(errorMessage);
      return null;
    }
  };

  return {
    groups,
    loading,
    createGroup,
    deleteGroup,
    addMembers,
    removeMember,
    regenerateInviteCode,
    refetch: fetchGroups,
  };
}
